Creating structures: List, BinaryTree, LinkedList, DoubleLinkedList, …
Tixon9I/LibraryClasses pull request #1
Opened 2024-07-04 13:56 UTC by Tixon9I

2024-07-05 08:38 UTC, Delvin09 requested changes

2024-07-05 08:38 UTC, Delvin09 commented on TestProject/LibraryClasses/BinaryTree.cs
> +        public int Value { get; set; }
думаю значение не должно меняться

2024-07-05 08:38 UTC, Delvin09 commented on TestProject/LibraryClasses/BinaryTree.cs
> +        public TreeNode Left { get; set; }
Left и Right могут быть null:
```
public TreeNode? Left { get; set; }
public TreeNode? Right { get; set; }
```

2024-07-05 08:38 UTC, Delvin09 commented on TestProject/LibraryClasses/BinaryTree.cs
> +        public TreeNode Left { get; set; }
тогда
`Left = null!;`
можно без !
`Left = null;`

2024-07-05 08:38 UTC, Delvin09 commented on TestProject/LibraryClasses/BinaryTree.cs
> +        private TreeNode Root { get; set; }
тоже может быть null

2024-07-05 08:38 UTC, Delvin09 commented on TestProject/LibraryClasses/DoublyLinkedList.cs
> +        public DoublyLinkedListNode Prev { get; set; }
тоже допускается null

2024-07-05 08:38 UTC, Delvin09 commented on TestProject/LibraryClasses/LinkedList.cs
> +        public LinkedListNode Next { get; set; }
`LinkedListNode?`

2024-07-05 08:38 UTC, Delvin09 commented on TestProject/LibraryClasses/LinkedList.cs
> +        internal LinkedListNode First { get; set; }
Почему internal ?

2024-07-05 08:38 UTC, Delvin09 commented on TestProject/LibraryClasses/LinkedList.cs
> +        public object Value { get; set; }
не думаю что оно может измениться

2024-07-05 08:38 UTC, Delvin09 commented on TestProject/LibraryClasses/DoublyLinkedList.cs
> +        internal new LinkedListNode First => base.First;
а зачем? зачем new? зачем создавать еще одни свойства, и вызывать базовые? Вроде и без этого все должно быть.

2024-07-05 08:38 UTC, Delvin09 commented on TestProject/LibraryClasses/DoublyLinkedList.cs
> +                base.First = newNode;
зачем base?
По идее, если уберешь Last, First, Count свойства в определении этого класса, то будут использоваться свойства из базового класса. Тогда base можно не писать. А  DoublyLinkedListNode может просто приводиться к базовому LinkedListNode.

2024-07-05 08:38 UTC, Delvin09 commented on TestProject/LibraryClasses/DoublyLinkedList.cs
> +                newNode.Next = (DoublyLinkedListNode)base.First;
по идее для Next тебе ничего не нужно приводить

2024-07-05 08:38 UTC, Delvin09 commented on TestProject/LibraryClasses/List.cs
> +        private object[]? _objects;
не думаю что _objects должно быть null, скорее пустым массивом

2024-07-05 08:38 UTC, Delvin09 commented on TestProject/LibraryClasses/List.cs
> +            if (!Contains(obj))
А зачем?

2024-07-05 08:38 UTC, Delvin09 commented on TestProject/LibraryClasses/List.cs
> +            foreach (var objct in _objects)
objct?

2024-07-05 08:38 UTC, Delvin09 commented on TestProject/LibraryClasses/List.cs
> +        public bool Contains(object obj)
Можно было тоже построить на базе IndexOf

2024-07-05 08:38 UTC, Delvin09 commented on TestProject/LibraryClasses/List.cs
> +            if (Contains(obj))
как то не оптимально, может лучше найти индекс, и тогда это будет означать что Contains вернул true

2024-07-05 08:38 UTC, Delvin09 commented on TestProject/LibraryClasses/List.cs
> +        public int Count { get => _count; }
Исходя из кода, немного путает использование и свойства и поля одновременно.
И тут можно или оставить только свойство, сделать его автоматическим, а сеттер приватным.
Или максимально не использовать в коде этого класса свойство, а только поле.

2024-07-05 08:38 UTC, Delvin09 commented on TestProject/LibraryClasses/Queue.cs
> +            if (_head == null || _tail == null)
сделай через тернарник

2024-07-05 08:38 UTC, Delvin09 commented on TestProject/TestProject/Program.cs
> +            //List list = new List(9);
лучше оставь не закоментированным. и раздели на методы, чтобы понимать где что тестируется

2024-07-06 10:09 UTC, Tixon9I commented on TestProject/LibraryClasses/BinaryTree.cs
> +        public int Value { get; set; }
resolved

2024-07-06 10:09 UTC, Tixon9I commented on TestProject/LibraryClasses/BinaryTree.cs
> +        public TreeNode Left { get; set; }
resolved

2024-07-06 10:09 UTC, Tixon9I commented on TestProject/LibraryClasses/BinaryTree.cs
> +        private TreeNode Root { get; set; }
resolved

2024-07-06 10:10 UTC, Tixon9I commented on TestProject/LibraryClasses/DoublyLinkedList.cs
> +        public DoublyLinkedListNode Prev { get; set; }
resolved

2024-07-06 10:46 UTC, Tixon9I commented on TestProject/LibraryClasses/LinkedList.cs
> +        public object Value { get; set; }
resolved

2024-07-06 10:47 UTC, Tixon9I commented on TestProject/LibraryClasses/DoublyLinkedList.cs
> +        internal new LinkedListNode First => base.First;
resolved

2024-07-06 10:49 UTC, Tixon9I commented on TestProject/LibraryClasses/DoublyLinkedList.cs
> +                base.First = newNode;
resolved

2024-07-06 10:50 UTC, Tixon9I commented on TestProject/LibraryClasses/DoublyLinkedList.cs
> +                newNode.Next = (DoublyLinkedListNode)base.First;
resolved

2024-07-06 10:50 UTC, Tixon9I commented on TestProject/LibraryClasses/List.cs
> +        private object[]? _objects;
resolved

2024-07-06 10:54 UTC, Tixon9I commented on TestProject/LibraryClasses/List.cs
> +        public int Count { get => _count; }
resolved

2024-07-06 11:02 UTC, Tixon9I commented on TestProject/LibraryClasses/Queue.cs
> +            if (_head == null || _tail == null)
resolved

2024-07-06 11:03 UTC, Tixon9I commented on TestProject/LibraryClasses/List.cs
> +            if (Contains(obj))
resolved

2024-07-06 11:17 UTC, Tixon9I commented on TestProject/LibraryClasses/List.cs
> +        public bool Contains(object obj)
resolved

2024-07-06 11:18 UTC, Tixon9I commented on TestProject/LibraryClasses/List.cs
> +            foreach (var objct in _objects)
resolved

2024-07-06 11:19 UTC, Tixon9I commented on TestProject/LibraryClasses/List.cs
> +            if (!Contains(obj))
resolved

2024-07-06 11:21 UTC, Tixon9I commented on TestProject/LibraryClasses/LinkedList.cs
> +        internal LinkedListNode First { get; set; }
resolved

2024-07-06 11:23 UTC, Tixon9I commented on TestProject/LibraryClasses/DoublyLinkedList.cs
> +        public DoublyLinkedListNode Prev { get; set; }
resolved

2024-07-06 11:23 UTC, Tixon9I commented on TestProject/LibraryClasses/BinaryTree.cs
> +        private TreeNode Root { get; set; }
resolved

2024-07-06 12:25 UTC, Tixon9I commented on TestProject/TestProject/Program.cs
> +            //List list = new List(9);
resolved

2024-07-06 13:47 UTC, Delvin09 approved these changes

2024-07-06 13:47 UTC, Delvin09 commented on TestProject/LibraryClasses/Queue.cs
> +            return (_head == null || _tail == null) ? false : Contains(_head, value);
а вот теперь можно убрать тернарник и просто возвращать значения.
`return _head != null && _tail != null && Contains(_head, value);`
или
`return Count > 0 && Contains(_head, value);`

2024-07-06 15:04 UTC, Tixon9I commented on TestProject/LibraryClasses/Queue.cs
> +            return (_head == null || _tail == null) ? false : Contains(_head, value);
resolved

2024-07-06 15:04 UTC, merged