Create interfaces for structures.
Tixon9I/LibraryClasses pull request #2
Opened 2024-07-09 16:37 UTC by Tixon9I

2024-07-10 06:39 UTC, Delvin09 requested changes

2024-07-10 06:39 UTC, Delvin09 commented on TestProject/LibraryClasses/Stack.cs
> +            return (Pop() is StackNode) ? true : false;
нет. тут именно найти и удалить нужно.
можно конечно и Pop() оставить, но возвращай тогда false когда Count <= 0

2024-07-10 06:39 UTC, Delvin09 commented on TestProject/LibraryClasses/Queue.cs
> +            return (Dequeue() is QueueNode) ? true : false;
то же, что и стека

2024-07-10 06:39 UTC, Delvin09 commented on TestProject/LibraryClasses/Interfaces/ICollection.cs
> +        void CopyTo(object[] array, int arrayIndex);
я предпологал что тут не CopyTo, а ToArray нужен

2024-07-10 06:39 UTC, Delvin09 commented on TestProject/LibraryClasses/Interfaces/ICollection.cs
> +        bool Remove(object item);
и мне кажется метод Remove тоже не должен быть тут.
ну или дерево должно иметь другой общий интерфейс с структурами данных.

немного странная ситуация, ты создала интерфейс, а потом подгоняешь под него классы.
Это не плохо, но лучше **выделять** интерфейсы из классов.

2024-07-10 06:39 UTC, Delvin09 commented on TestProject/LibraryClasses/Interfaces/ICollection.cs
> +        bool Remove(object item);
Пусть уже будет так,

2024-07-10 06:39 UTC, Delvin09 commented on TestProject/LibraryClasses/BinaryTree.cs
> +        public int Value { get; set; }
set?

2024-07-10 06:39 UTC, Delvin09 commented on TestProject/LibraryClasses/LinkedList.cs
> +        object? ILinkedList.First => First;
ух....
ну во первых можно просто создать два поля для first и last нодов.
а свойства пусть идут в эти поля и достают значения.
а так у тебя ноды возвращаются, что не правильно, так как класс ноды скрыт в классе списка.

2024-07-10 06:39 UTC, Delvin09 commented on TestProject/LibraryClasses/DoublyLinkedList.cs
> +            ((DoublyLinkedListNode)newNode).Prev = current;
У тебя Insert отличатся начинает тут. Можно все что выше вынести в базовый класс
А то что ниже можно свести к нескольким вызовам UpdateNode, и тоже перенести на базовый уровень

2024-07-10 06:39 UTC, Delvin09 commented on TestProject/LibraryClasses/DoublyLinkedList.cs
> +            ((DoublyLinkedListNode)newNode).Prev = current;
```
UpdateNode(newNode, next: current?.Next, prev: current);
UpdateNode(current, next: newNode, skipPrev: true);
UpdateNode(current.Next, prev: newNode, skipNext: true);
```

2024-07-10 06:39 UTC, Delvin09 commented on TestProject/LibraryClasses/DoublyLinkedList.cs
> +            ((DoublyLinkedListNode)newNode).Prev = current;
правда нужно UpdateNode допилить. добавить скип параметры для next и prev

2024-07-10 10:17 UTC, Tixon9I commented on TestProject/LibraryClasses/Stack.cs
> +            return (Pop() is StackNode) ? true : false;
resolved

2024-07-10 10:18 UTC, Tixon9I commented on TestProject/LibraryClasses/Queue.cs
> +            return (Dequeue() is QueueNode) ? true : false;
resolved

2024-07-10 10:18 UTC, Tixon9I commented on TestProject/LibraryClasses/Interfaces/ICollection.cs
> +        void CopyTo(object[] array, int arrayIndex);
resolved

2024-07-10 10:18 UTC, Tixon9I commented on TestProject/LibraryClasses/Interfaces/ICollection.cs
> +        bool Remove(object item);
resolved

2024-07-10 10:23 UTC, Tixon9I commented on TestProject/LibraryClasses/BinaryTree.cs
> +        public int Value { get; set; }
Через метод Remove прийшлось зробити такі зміни, але я повернула минулий стан цієї властивості. resolved

2024-07-10 10:36 UTC, Tixon9I commented on TestProject/LibraryClasses/LinkedList.cs
> +        object? ILinkedList.First => First;
resolved

2024-07-11 08:52 UTC, Delvin09 approved these changes

2024-07-11 08:52 UTC, Delvin09 commented on TestProject/LibraryClasses/Interfaces/ICollection.cs
> +        //bool Remove(object item);
не оставляй закоментированный код без веской причины

2024-07-11 09:29 UTC, merged